In [20]:
import torch
import numpy as np
np_data = np.arange(6).reshape((3,-1))
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy()
print(
    '\n',np_data,
    '\n',torch_data,
    '\n',tensor2array
)


 [[0 1]
 [2 3]
 [4 5]] 
 tensor([[0, 1],
        [2, 3],
        [4, 5]]) 
 [[0 1]
 [2 3]
 [4 5]]


In [17]:
#矩阵点乘
data = [[1,2],[3,4]]
tensor = torch.FloatTensor(data)
print(
    torch.mm(tensor,tensor)
)

tensor([[ 7., 10.],
        [15., 22.]])


In [23]:
from torch.autograd import Variable
tensor_1 = torch.FloatTensor([[1,2],[3,4]]) 
variable = Variable(tensor,requires_grad = True)
print(tensor_1)
print(variable)
t_out = torch.mean(tensor_1*tensor_1)
v_out = torch.mean(variable*variable)
print(t_out)
print(v_out)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward1>)


In [33]:
#获取variable数据
print(variable)
#转变为tensor形式
print(variable.data)
#转变为numpy形式
print(variable.data.numpy())

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[1., 2.],
        [3., 4.]])
[[1. 2.]
 [3. 4.]]
